# Generated by Django 5.2.7 on 2025-10-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subttile", models.CharField(blank=True, max_length=200, null=True)),
                ("author", models.CharField(max_length=100)),
                ("published_date", models.DateField()),
                ("isbn_number", models.CharField(max_length=13, unique=True)),
                ("pages", models.IntegerField()),
                ("cover_image", models.URLField(blank=True, null=True)),
                ("language", models.CharField(max_length=30)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
