# Generated by Django 5.2.7 on 2025-10-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="subttile",
            new_name="subtile",
        ),
    ]
