# Generated by Django 5.2.7 on 2025-10-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_rename_subttile_book_subtile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="subtile",
            new_name="subtitle",
        ),
    ]
