# Generated by Django 5.2.8 on 2025-11-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_rename_subtile_book_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
